# Generated by Django 5.1.6 on 2025-02-09 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itenscompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='livro',
        ),
    ]
